# Generated by Django 3.2.12 on 2022-03-09 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardians', '0001_initial'),
        ('plans', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
        migrations.AddField(
            model_name='order',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardians.guardian'),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.orderdetail'),
        ),
    ]
