# Generated by Django 3.2.12 on 2022-03-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='trial_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'CARD'), ('PAYPAL', 'PAYPAL'), ('APPLEPAY', 'APPLEPAY'), ('FREE', 'FREE')], default='CARD', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(choices=[('CARD', 'CARD'), ('PAYPAL', 'PAYPAL'), ('APPLEPAY', 'APPLEPAY'), ('FREE', 'FREE')], default='CARD', max_length=255),
        ),
    ]
