# Generated by Django 3.2.12 on 2022-05-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_orderdetail_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='customer_id',
        ),
    ]
