# Generated by Django 3.2.12 on 2022-05-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_orderdetail_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
