# Generated by Django 3.2.12 on 2022-03-09 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kb', '0001_initial'),
        ('plans', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianstudentplan',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
        migrations.AddField(
            model_name='guardianstudentplan',
            name='subject',
            field=models.ManyToManyField(blank=True, to='kb.AreaOfKnowledge'),
        ),
    ]
