# Generated by Django 3.2.12 on 2022-03-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardianstudentplan',
            name='expired_at',
        ),
        migrations.RemoveField(
            model_name='guardianstudentplan',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='guardianstudentplan',
            name='period',
        ),
        migrations.RemoveField(
            model_name='guardianstudentplan',
            name='price',
        ),
    ]
