# Generated by Django 3.2.12 on 2022-03-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiblecategory',
            name='firebase_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
