# Generated by Django 3.2.12 on 2022-03-09 02:36

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0002_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayGameTransaction',
            fields=[
                ('withdraw_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallets.withdraw')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='games.game')),
            ],
            options={
                'abstract': False,
            },
            bases=('wallets.withdraw',),
        ),
        migrations.AddField(
            model_name='gametranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='games.game'),
        ),
        migrations.AddField(
            model_name='gamecategorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='games.gamecategory'),
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(to='games.GameCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='gametranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='gamecategorytranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
