# Generated by Django 3.2.12 on 2022-04-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
