# Generated by Django 3.2.12 on 2022-03-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfKnowledgeStudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('questions_answered', models.IntegerField(default=0)),
                ('correct_question', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicMasterySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_size', models.IntegerField(default=50)),
                ('mastery_percentage', models.IntegerField(default=90)),
                ('competence_percentage', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='TopicStudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('questions_answered', models.IntegerField(default=0)),
                ('correct_question', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
