# Generated by Django 3.2.12 on 2022-03-09 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0001_initial'),
        ('kb', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicstudentreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
        migrations.AddField(
            model_name='topicstudentreport',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.topic'),
        ),
        migrations.AddField(
            model_name='topicmasterysettings',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='kb.topic'),
        ),
        migrations.AddField(
            model_name='areaofknowledgestudentreport',
            name='area_of_knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.areaofknowledge'),
        ),
        migrations.AddField(
            model_name='areaofknowledgestudentreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
    ]
