# Generated by Django 3.2.12 on 2022-03-22 18:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofknowledgestudentreport',
            name='accuracy',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3),
        ),
        migrations.AlterField(
            model_name='topicstudentreport',
            name='accuracy',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3),
        ),
    ]
