# Generated by Django 3.2.12 on 2022-03-23 03:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20220322_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofknowledgestudentreport',
            name='accuracy',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='topicstudentreport',
            name='accuracy',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=4),
        ),
    ]
