# Generated by Django 3.2.12 on 2022-03-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='standard_topic',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
