# Generated by Django 3.2.12 on 2022-03-15 23:38

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    MyModel = apps.get_model('kb', 'AnswerOption')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    new_ct = ContentType.objects.get_for_model(MyModel)
    MyModel.objects.filter(polymorphic_ctype__isnull=True).update(
        polymorphic_ctype=new_ct)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kb', '0002_topic_standard_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='polymorphic_kb.answeroption_set+', to='contenttypes.contenttype'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
