# Generated by Django 3.2.12 on 2022-03-25 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_topic_standard_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisite',
            name='create_timestamp',
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='deleted_timestamp',
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='update_timestamp',
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Topic', to='kb.topic'),
        ),
    ]
