# Generated by Django 3.2.12 on 2022-03-16 00:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_answeroption_polymorphic_ctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceAnswerOptionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('answer_text', models.CharField(max_length=256)),
                ('explanation', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
                ('video', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'multiple choice answer option Translation',
                'db_table': 'kb_multiplechoiceansweroption_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='answeroption',
            name='is_correct',
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswerOption',
            fields=[
                ('answeroption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kb.answeroption')),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('kb.answeroption', models.Model),
        ),
        migrations.DeleteModel(
            name='AnswerOptionTranslation',
        ),
        migrations.AddField(
            model_name='multiplechoiceansweroptiontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='kb.multiplechoiceansweroption'),
        ),
        migrations.AlterUniqueTogether(
            name='multiplechoiceansweroptiontranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
