# Generated by Django 3.2.12 on 2022-03-30 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_auto_20220324_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePrerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('random_slug', models.UUIDField(editable=False, unique=True)),
                ('area_of_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.areaofknowledge')),
                ('competence', models.ManyToManyField(related_name='competence_start', to='kb.Topic')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.grade')),
                ('mastery', models.ManyToManyField(related_name='mastery_start', to='kb.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
