# Generated by Django 3.2.12 on 2022-03-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_gradeprerequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeprerequisite',
            name='competence',
            field=models.ManyToManyField(blank=True, related_name='competence_start', to='kb.Topic'),
        ),
        migrations.AlterField(
            model_name='gradeprerequisite',
            name='mastery',
            field=models.ManyToManyField(blank=True, related_name='mastery_start', to='kb.Topic'),
        ),
    ]
