# Generated by Django 3.2.12 on 2022-03-16 00:18

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_auto_20220315_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAnswerOption',
            fields=[
                ('answeroption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kb.answeroption')),
                ('order', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('kb.answeroption', models.Model),
        ),
        migrations.CreateModel(
            name='OrderAnswerOptionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('answer_text', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
                ('video', models.URLField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='kb.orderansweroption')),
            ],
            options={
                'verbose_name': 'order answer option Translation',
                'db_table': 'kb_orderansweroption_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
