# Generated by Django 3.2.12 on 2022-03-16 18:28

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0005_orderansweroption_orderansweroptiontranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedAnswerOption',
            fields=[
                ('answeroption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kb.answeroption')),
            ],
            options={
                'abstract': False,
            },
            bases=('kb.answeroption', models.Model),
        ),
        migrations.AlterField(
            model_name='multiplechoiceansweroptiontranslation',
            name='audio_file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoiceansweroptiontranslation',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderansweroptiontranslation',
            name='audio_file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderansweroptiontranslation',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RelatedAnswerOptionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('key_image', models.URLField(blank=True, null=True)),
                ('value_image', models.URLField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='kb.relatedansweroption')),
            ],
            options={
                'verbose_name': 'related answer option Translation',
                'db_table': 'kb_relatedansweroption_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
