# Generated by Django 3.2.12 on 2022-04-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0006_auto_20220404_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='standard_topic',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
