# Generated by Django 3.2.12 on 2022-03-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_merge_20220311_1319'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('kb', '0006_auto_20220316_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelatedAnswerOption',
            new_name='RelateAnswerOption',
        ),
        migrations.RenameModel(
            old_name='RelatedAnswerOptionTranslation',
            new_name='RelateAnswerOptionTranslation',
        ),
        migrations.AlterModelOptions(
            name='relateansweroptiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'relate answer option Translation'},
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('O', 'Order'), ('R', 'Relate')], default='MC', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='relateansweroptiontranslation',
            table='kb_relateansweroption_translation',
        ),
    ]
