# Generated by Django 3.2.12 on 2022-03-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0007_auto_20220316_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('MS', 'Multiple Select'), ('O', 'Order'), ('R', 'Relate')], max_length=2),
        ),
    ]
