# Generated by Django 3.2.12 on 2022-03-17 19:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0008_alter_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleSelectAnswerOption',
            fields=[
                ('answeroption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kb.answeroption')),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('kb.answeroption',),
        ),
        migrations.CreateModel(
            name='TypeInAnswerOption',
            fields=[
                ('answeroption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kb.answeroption')),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('kb.answeroption',),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('MS', 'Multiple Select'), ('O', 'Order'), ('R', 'Relate'), ('T', 'Type In')], max_length=2),
        ),
        migrations.CreateModel(
            name='TypeInAnswerOptionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('answer_text', models.CharField(max_length=256)),
                ('explanation', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('audio_file', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='kb.typeinansweroption')),
            ],
            options={
                'verbose_name': 'type in answer option Translation',
                'db_table': 'kb_typeinansweroption_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MultipleSelectAnswerOptionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('answer_text', models.CharField(max_length=256)),
                ('explanation', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('audio_file', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='kb.multipleselectansweroption')),
            ],
            options={
                'verbose_name': 'multiple select answer option Translation',
                'db_table': 'kb_multipleselectansweroption_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
