# Generated by Django 3.2.12 on 2022-04-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0007_alter_topic_standard_topic'),
        ('kb', '0009_auto_20220317_1258'),
    ]

    operations = [
    ]
