# Generated by Django 3.2.12 on 2022-04-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0010_merge_20220411_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeroption',
            name='tts_file',
        ),
    ]
