# Generated by Django 3.2.12 on 2022-04-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0012_auto_20220411_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeinansweroption',
            name='case_sensitive',
            field=models.BooleanField(default=False),
        ),
    ]
