# Generated by Django 3.2.12 on 2022-05-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kb', '0013_typeinansweroption_case_sensitive'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('answer_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.answeroption')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_kb.answerasset_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnswerTTSAsset',
            fields=[
                ('answerasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kb.answerasset')),
                ('tts_file', models.FileField(blank=True, null=True, upload_to='tts')),
            ],
            options={
                'abstract': False,
            },
            bases=('kb.answerasset',),
        ),
    ]
