# Generated by Django 3.2.12 on 2022-05-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0014_answerasset_answerttsasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerttsasset',
            name='language',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='questionttsasset',
            name='language',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
