# Generated by Django 3.2.12 on 2022-04-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_auto_20220419_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyTreasureWallet',
        ),
    ]
