# Generated by Django 3.2.12 on 2022-04-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_guardianstudentplan_student'),
        ('payments', '0003_auto_20220314_1014'),
        ('audiences', '0001_initial'),
        ('kb', '0013_typeinansweroption_case_sensitive'),
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='group',
        ),
        migrations.RemoveField(
            model_name='school',
            name='student',
        ),
        migrations.AddField(
            model_name='group',
            name='school_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.schoolpersonnel'),
        ),
        migrations.AddField(
            model_name='schoolpersonnel',
            name='country',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='schoolpersonnel',
            name='discountCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.discountcode'),
        ),
        migrations.AddField(
            model_name='schoolpersonnel',
            name='district',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='schoolpersonnel',
            name='zip',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='student_plan',
            field=models.ManyToManyField(blank=True, to='plans.StudentPlan'),
        ),
        migrations.AlterField(
            model_name='school',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='school',
            name='student_plan',
            field=models.ManyToManyField(to='plans.StudentPlan'),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('name', models.CharField(max_length=128, null=True)),
                ('language', models.CharField(max_length=128, null=True)),
                ('enable_games', models.BooleanField(default=True)),
                ('game_cost', models.IntegerField(blank=True, null=True)),
                ('time_zone', models.CharField(max_length=128, null=True)),
                ('monday_start', models.TimeField(null=True)),
                ('monday_end', models.TimeField(null=True)),
                ('tuesday_start', models.TimeField(null=True)),
                ('tuesday_end', models.TimeField(null=True)),
                ('wednesday_start', models.TimeField(null=True)),
                ('wednesday_end', models.TimeField(null=True)),
                ('thursday_start', models.TimeField(null=True)),
                ('thursday_end', models.TimeField(null=True)),
                ('friday_start', models.TimeField(null=True)),
                ('friday_end', models.TimeField(null=True)),
                ('saturday_start', models.TimeField(null=True)),
                ('saturday_end', models.TimeField(null=True)),
                ('sunday_start', models.TimeField(null=True)),
                ('sunday_end', models.TimeField(null=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audiences.audience')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.grade')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.school')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
