# Generated by Django 3.2.12 on 2022-03-09 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('name', models.CharField(max_length=128)),
                ('positive_side', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('I', 'I')], default='R', max_length=16)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha Movimiento')),
                ('side', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('I', 'I')], max_length=1, verbose_name='Lado')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='Comentario')),
                ('amount', models.FloatField()),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha Movimiento')),
                ('side', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('I', 'I')], max_length=1, verbose_name='Lado')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='Comentario')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Monto')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BankNegativeMovement',
            fields=[
                ('bankmovement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.bankmovement')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounting.bankmovement',),
        ),
        migrations.CreateModel(
            name='BankPositiveMovement',
            fields=[
                ('bankmovement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.bankmovement')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounting.bankmovement',),
        ),
    ]
