# Generated by Django 3.2.12 on 2022-05-19 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bankwallet_student'),
        ('wallets', '0004_delete_dailytreasurewallet'),
        ('accounting', '0003_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmovement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bankwallet', verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='bankmovement',
            name='amount',
            field=models.FloatField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='bankmovement',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='bankmovement',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='movement date'),
        ),
        migrations.AlterField(
            model_name='bankmovement',
            name='side',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('I', 'I')], max_length=1, verbose_name='side'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.coinwallet', verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='movement date'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='side',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('I', 'I')], max_length=1, verbose_name='side'),
        ),
    ]
