# Generated by Django 3.2.12 on 2022-03-14 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20220314_1014'),
        ('guardians', '0003_guardian_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.discountcode'),
        ),
    ]
