# Generated by Django 3.2.12 on 2022-03-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardians', '0004_guardian_coupon_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='name',
            new_name='first_name',
        ),
    ]
