# Generated by Django 3.2.12 on 2022-03-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.UUIDField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('type_of', models.CharField(choices=[('ACCESSORIES', 'Accessories'), ('HEAD', 'Head/Hair'), ('CLOTHES', 'Clothes'), ('PANTS', 'Pants')], max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.URLField(null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
