# Generated by Django 3.2.12 on 2022-03-09 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_user'),
        ('avatars', '0001_initial'),
        ('wallets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('in_use', models.BooleanField(default=False)),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='avatars.avatar')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteAvatarCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('skin_tone', models.CharField(blank=True, max_length=7, null=True)),
                ('avatar_accessorie', models.ForeignKey(blank=True, limit_choices_to={'type_of': 'ACCESSORIES'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar')),
                ('avatar_clothes', models.ForeignKey(limit_choices_to={'type_of': 'CLOTHES'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar')),
                ('avatar_head', models.ForeignKey(limit_choices_to={'type_of': 'HEAD'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar')),
                ('avatar_pants', models.ForeignKey(limit_choices_to={'type_of': 'PANTS'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvatarPurchaseTransaction',
            fields=[
                ('withdraw_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallets.withdraw')),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='avatars.avatar')),
            ],
            options={
                'abstract': False,
            },
            bases=('wallets.withdraw',),
        ),
    ]
