# Generated by Django 3.2.12 on 2022-03-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockquestionpresentation',
            name='deleted_timestamp',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp'),
        ),
        migrations.AddField(
            model_name='blockquestionpresentation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blockquestionpresentation',
            name='block_presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='block.blockpresentation'),
        ),
    ]
