# Generated by Django 3.2.12 on 2022-03-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_alter_blockquestionpresentation_block_presentation'),
        ('block', '0003_auto_20220311_1233'),
    ]

    operations = [
    ]
