# Generated by Django 3.2.12 on 2022-04-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0012_auto_20220411_1549'),
        ('block', '0004_merge_20220311_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockquestionpresentation',
            name='chosen_answer',
        ),
        migrations.AddField(
            model_name='blockquestionpresentation',
            name='chosen_answer',
            field=models.ManyToManyField(to='kb.AnswerOption'),
        ),
    ]
