# Generated by Django 3.2.12 on 2022-04-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_auto_20220411_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockquestionpresentation',
            name='typed_answer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
