# Generated by Django 3.2.12 on 2022-04-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0006_blockquestionpresentation_typed_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='modality',
            field=models.CharField(choices=[('AI', 'AI'), ('PATH', 'Choose your path'), ('HOMEWORK', 'Homework'), ('TEST', 'Test')], default='AI', max_length=128),
        ),
    ]
