# Generated by Django 3.2.12 on 2022-05-19 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_classroom'),
        ('block', '0007_alter_block_modality'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBlockQuestionPresentationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('block_question_presentation', models.ManyToManyField(to='block.BlockQuestionPresentation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
