# Generated by Django 3.2.12 on 2022-03-09 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0001_initial'),
        ('avatars', '0001_initial'),
        ('plans', '0001_initial'),
        ('achievements', '0001_initial'),
        ('organization', '0001_initial'),
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.UUIDField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('full_name', models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=8, null=True)),
                ('points', models.IntegerField(default=0)),
                ('int_period_start_at', models.DateField(auto_now_add=True)),
                ('active_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_group', to='organization.group')),
                ('active_student_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_student_plan', to='plans.studentplan')),
                ('avatar_accessories', models.ForeignKey(blank=True, limit_choices_to={'type_of': 'ACCESSORIES'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar')),
                ('avatar_clothes', models.ForeignKey(blank=True, limit_choices_to={'type_of': 'CLOTHES'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar')),
                ('avatar_head', models.ForeignKey(blank=True, limit_choices_to={'type_of': 'HEAD'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar')),
                ('avatar_pants', models.ForeignKey(blank=True, limit_choices_to={'type_of': 'PANTS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar')),
                ('group', models.ManyToManyField(blank=True, to='organization.Group')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='experiences.level')),
                ('student_plan', models.ManyToManyField(to='plans.StudentPlan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTopicStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('status', models.CharField(choices=[('B', 'Blocked'), ('P', 'Preview'), ('A', 'Available')], default='B', max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='kb.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTopicMastery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.UUIDField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('mastery_level', models.CharField(choices=[('NP', 'Not practiced'), ('N', 'Novice'), ('C', 'Competent'), ('M', 'Master')], default='NP', max_length=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mastery', to='kb.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.UUIDField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('is_finished', models.IntegerField(null=True)),
                ('percentage', models.FloatField(null=True)),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kb.grade')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.UUIDField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('is_liberate', models.IntegerField(null=True)),
                ('liberation_date', models.DateField(blank=True, null=True)),
                ('achivement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='achievements.achievement')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
