# Generated by Django 3.2.12 on 2022-03-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttopicmastery',
            name='deleted_timestamp',
        ),
        migrations.RemoveField(
            model_name='studenttopicmastery',
            name='is_active',
        ),
    ]
