# Generated by Django 3.2.12 on 2022-03-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20220314_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='avatar_accessories',
        ),
        migrations.RemoveField(
            model_name='student',
            name='avatar_clothes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='avatar_head',
        ),
        migrations.RemoveField(
            model_name='student',
            name='avatar_pants',
        ),
    ]
