# Generated by Django 3.2.12 on 2022-03-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttopicmastery',
            name='is_forced',
            field=models.BooleanField(default=False),
        ),
    ]
