# Generated by Django 3.2.12 on 2022-03-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studenttopicmastery_is_forced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttopicmastery',
            name='is_forced',
        ),
    ]
