# Generated by Django 3.2.12 on 2022-04-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_studenttopicmastery_is_forced'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
