# Generated by Django 3.2.12 on 2022-04-19 23:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectibles', '0003_collectiblecategory_firebase_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTreasureLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('coins_required', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyTreasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('coins_awarded', models.PositiveIntegerField(blank=True, null=True)),
                ('collectibles_awarded', models.ManyToManyField(to='collectibles.Collectible')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasuretrack.dailytreasurelevel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
