# Generated by Django 3.2.12 on 2022-04-19 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasuretrack', '0002_auto_20220419_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytreasurelevel',
            name='level',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
