# Generated by Django 3.2.12 on 2022-04-20 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasuretrack', '0004_alter_dailytreasurelevel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytreasurelevel',
            name='level',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
