# Generated by Django 3.2.12 on 2022-04-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_is_new'),
        ('wallets', '0004_delete_dailytreasurewallet'),
        ('treasuretrack', '0005_alter_dailytreasurelevel_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDailyTreasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('daily_treasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasuretrack.dailytreasure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyTreasureTransaction',
            fields=[
                ('deposit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallets.deposit')),
                ('daily_treasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasuretrack.studentdailytreasure')),
            ],
            options={
                'abstract': False,
            },
            bases=('wallets.deposit',),
        ),
    ]
