# Generated by Django 3.2.12 on 2022-04-20 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasuretrack', '0007_alter_dailytreasurelevel_coins_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytreasurelevel',
            name='coins_required',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dailytreasurelevel',
            name='level',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
