# Generated by Django 3.2.12 on 2022-04-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0003_collectiblecategory_firebase_name'),
        ('treasuretrack', '0009_alter_dailytreasurelevel_coins_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytreasure',
            name='collectibles_awarded',
            field=models.ManyToManyField(blank=True, to='collectibles.Collectible'),
        ),
    ]
