# Generated by Django 3.2.12 on 2022-04-29 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_classroom'),
        ('wallets', '0004_delete_dailytreasurewallet'),
        ('collectibles', '0003_collectiblecategory_firebase_name'),
        ('treasuretrack', '0010_alter_dailytreasure_collectibles_awarded'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWeeklyTreasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyTreasureTransaction',
            fields=[
                ('deposit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallets.deposit')),
                ('weekly_treasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasuretrack.studentweeklytreasure')),
            ],
            options={
                'abstract': False,
            },
            bases=('wallets.deposit',),
        ),
        migrations.RenameModel(
            old_name='DailyTreasureLevel',
            new_name='WeeklyTreasureLevel',
        ),
        migrations.RemoveField(
            model_name='studentdailytreasure',
            name='daily_treasure',
        ),
        migrations.RemoveField(
            model_name='studentdailytreasure',
            name='student',
        ),
        migrations.RenameModel(
            old_name='DailyTreasure',
            new_name='WeeklyTreasure',
        ),
        migrations.DeleteModel(
            name='DailyTreasureTransaction',
        ),
        migrations.DeleteModel(
            name='StudentDailyTreasure',
        ),
        migrations.AddField(
            model_name='studentweeklytreasure',
            name='weekly_treasure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasuretrack.weeklytreasure'),
        ),
    ]
