# Generated by Django 3.2.12 on 2022-04-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0003_collectiblecategory_firebase_name'),
        ('treasuretrack', '0011_auto_20220429_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytreasurelevel',
            name='bonus_coins',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklytreasurelevel',
            name='bonus_collectible',
            field=models.ManyToManyField(blank=True, to='collectibles.Collectible'),
        ),
        migrations.AddField(
            model_name='weeklytreasurelevel',
            name='correct_questions_required',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
