# Generated by Django 3.2.12 on 2022-04-30 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasuretrack', '0012_auto_20220430_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklytreasuretransaction',
            old_name='weekly_treasure',
            new_name='student_weekly_treasure',
        ),
    ]
