# Generated by Django 3.2.12 on 2022-05-04 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_badge_type'),
        ('treasuretrack', '0013_rename_weekly_treasure_weeklytreasuretransaction_student_weekly_treasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytreasure',
            name='badge_awarded',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='badges.badge'),
        ),
        migrations.AddField(
            model_name='weeklytreasurelevel',
            name='bonus_badge',
            field=models.ManyToManyField(blank=True, null=True, to='badges.Badge'),
        ),
    ]
